package streamnx

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/GeorgeGorbanev/streamnx/internal/youtube"
)

func TestYoutubeAdapter_FetchTrack(t *testing.T) {
	tests := []struct {
		name          string
		id            string
		mockClient    func(m *youtube.ClientMock)
		expectedTrack *Entity
		expectedErr   error
	}{
		{
			name: "found ID",
			id:   "sampleID",
			mockClient: func(m *youtube.ClientMock) {
				m.
					On("GetVideo", "sampleID").
					Return(&youtube.Video{
						ID:    "sampleID",
						Title: "sample artist – sample track",
					}, nil).
					Once()
			},
			expectedTrack: &Entity{
				ID:       "sampleID",
				Title:    "sample track",
				Artist:   "sample artist",
				URL:      "https://www.youtube.com/watch?v=sampleID",
				Provider: Youtube,
				Type:     Track,
			},
		},
		{
			name: "found ID autogenerated track video",
			id:   "sampleID",
			mockClient: func(m *youtube.ClientMock) {
				m.
					On("GetVideo", "sampleID").
					Return(&youtube.Video{
						ID:           "sampleID",
						Title:        "track name (remastered)",
						Description:  "bla bla bla. Auto-generated by YouTube",
						ChannelTitle: "sample artist - Topic",
					}, nil).
					Once()
			},
			expectedTrack: &Entity{
				ID:       "sampleID",
				Title:    "track name",
				Artist:   "sample artist",
				URL:      "https://www.youtube.com/watch?v=sampleID",
				Provider: Youtube,
				Type:     Track,
			},
		},
		{
			name: "not found ID",
			id:   "notFoundID",
			mockClient: func(m *youtube.ClientMock) {
				m.
					On("GetVideo", "notFoundID").
					Return(nil, youtube.NotFoundError).
					Once()
			},
			expectedTrack: nil,
			expectedErr:   EntityNotFoundError,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			clientMock := &youtube.ClientMock{}
			tt.mockClient(clientMock)

			a := newYoutubeAdapter(clientMock)

			result, err := a.FetchTrack(t.Context(), tt.id)

			if tt.expectedErr != nil {
				require.ErrorIs(t, err, tt.expectedErr)
			} else {
				require.NoError(t, err)
				require.Equal(t, tt.expectedTrack, result)
			}

			clientMock.AssertExpectations(t)
		})
	}
}

func TestYoutubeAdapter_SearchTrack(t *testing.T) {
	tests := []struct {
		name          string
		artist        string
		searchName    string
		mockClient    func(m *youtube.ClientMock)
		expectedTrack *Entity
		expectedErr   error
	}{
		{
			name:       "found query",
			artist:     "sample artist",
			searchName: "sample track",
			mockClient: func(m *youtube.ClientMock) {
				m.
					On("SearchVideo", "sample artist – sample track").
					Return(&youtube.SearchResponse{
						Items: []youtube.SearchItem{
							{
								ID: youtube.SearchID{
									VideoID: "sampleID",
								},
							},
						},
					}, nil).
					Once()
				m.
					On("GetVideo", "sampleID").
					Return(&youtube.Video{
						ID:    "sampleID",
						Title: "sample artist – sample track",
					}, nil).
					Once()
			},
			expectedTrack: &Entity{
				ID:       "sampleID",
				Title:    "sample track",
				Artist:   "sample artist",
				URL:      "https://www.youtube.com/watch?v=sampleID",
				Provider: Youtube,
				Type:     Track,
			},
		},
		{
			name:       "not found query",
			artist:     "not found artist",
			searchName: "not found name",
			mockClient: func(m *youtube.ClientMock) {
				m.
					On("SearchVideo", "not found artist – not found name").
					Return(nil, youtube.NotFoundError).
					Once()
			},
			expectedTrack: nil,
			expectedErr:   EntityNotFoundError,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			clientMock := &youtube.ClientMock{}
			tt.mockClient(clientMock)

			a := newYoutubeAdapter(clientMock)

			result, err := a.SearchTrack(t.Context(), tt.artist, tt.searchName)

			if tt.expectedErr != nil {
				require.ErrorIs(t, err, tt.expectedErr)
			} else {
				require.NoError(t, err)
				require.Equal(t, tt.expectedTrack, result)
			}

			clientMock.AssertExpectations(t)
		})
	}
}

func TestYoutubeAdapter_FetchAlbum(t *testing.T) {
	tests := []struct {
		name          string
		id            string
		mockClient    func(m *youtube.ClientMock)
		expectedAlbum *Entity
		expectedErr   error
	}{
		{
			name: "found ID",
			id:   "sampleID",
			mockClient: func(m *youtube.ClientMock) {
				m.
					On("GetPlaylist", "sampleID").
					Return(&youtube.Playlist{
						ID:    "sampleID",
						Title: "sample artist – sample album",
					}, nil).
					Once()
			},
			expectedAlbum: &Entity{
				ID:       "sampleID",
				Title:    "sample album",
				Artist:   "sample artist",
				URL:      "https://www.youtube.com/playlist?list=sampleID",
				Provider: Youtube,
				Type:     Album,
			},
		},
		{
			name: "found ID autogenerated album playlist",
			id:   "sampleID",
			mockClient: func(m *youtube.ClientMock) {
				m.
					On("GetPlaylist", "sampleID").
					Return(&youtube.Playlist{
						ID:    "sampleID",
						Title: "Album - sample album",
					}, nil).
					Once()
				m.
					On("GetPlaylistItems", "sampleID").
					Return([]youtube.Video{
						{
							ID:           "sampleTrackID",
							Title:        "sample track",
							ChannelTitle: "sample artist - Topic",
							Description:  "bla bla bla Auto-generated by YouTube bla bla bla",
						},
					}, nil).
					Once()
			},
			expectedAlbum: &Entity{
				ID:       "sampleID",
				Title:    "sample album",
				Artist:   "sample artist",
				URL:      "https://www.youtube.com/playlist?list=sampleID",
				Provider: Youtube,
				Type:     Album,
			},
		},
		{
			name: "found ID autogenerated album playlist empty",
			id:   "sampleID",
			mockClient: func(m *youtube.ClientMock) {
				m.
					On("GetPlaylist", "sampleID").
					Return(&youtube.Playlist{
						ID:    "sampleID",
						Title: "Album - sample album",
					}, nil).
					Once()
				m.
					On("GetPlaylistItems", "sampleID").
					Return([]youtube.Video{}, nil).
					Once()
			},
			expectedAlbum: &Entity{
				ID:       "sampleID",
				Title:    "sample album",
				Artist:   "Album",
				URL:      "https://www.youtube.com/playlist?list=sampleID",
				Provider: Youtube,
				Type:     Album,
			},
		},
		{
			name: "found ID autogenerated album not autogenerated track",
			id:   "sampleID",
			mockClient: func(m *youtube.ClientMock) {
				m.
					On("GetPlaylist", "sampleID").
					Return(&youtube.Playlist{
						ID:    "sampleID",
						Title: "Album - sample album",
					}, nil).
					Once()
				m.
					On("GetPlaylistItems", "sampleID").
					Return([]youtube.Video{
						{
							ID:           "sampleTrackID",
							Title:        "sample track",
							ChannelTitle: "sample artist - Topic",
							Description:  "any not autogenerated description",
						},
					}, nil).
					Once()
			},
			expectedAlbum: &Entity{
				ID:       "sampleID",
				Title:    "sample album",
				Artist:   "Album",
				URL:      "https://www.youtube.com/playlist?list=sampleID",
				Provider: Youtube,
				Type:     Album,
			},
		},
		{
			name: "not found ID",
			id:   "notFoundID",
			mockClient: func(m *youtube.ClientMock) {
				m.
					On("GetPlaylist", "notFoundID").
					Return(nil, youtube.NotFoundError).
					Once()
			},
			expectedAlbum: nil,
			expectedErr:   EntityNotFoundError,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			clientMock := &youtube.ClientMock{}
			tt.mockClient(clientMock)

			a := newYoutubeAdapter(clientMock)

			result, err := a.FetchAlbum(t.Context(), tt.id)

			if tt.expectedErr != nil {
				require.ErrorIs(t, err, tt.expectedErr)
			} else {
				require.NoError(t, err)
				require.Equal(t, tt.expectedAlbum, result)
			}

			clientMock.AssertExpectations(t)
		})
	}
}

func TestYoutubeAdapter_SearchAlbum(t *testing.T) {
	tests := []struct {
		name          string
		artist        string
		searchName    string
		mockClient    func(m *youtube.ClientMock)
		expectedAlbum *Entity
		expectedErr   error
	}{
		{
			name:       "found query",
			artist:     "sample artist",
			searchName: "sample album",
			mockClient: func(m *youtube.ClientMock) {
				m.
					On("SearchPlaylist", "sample artist – sample album").
					Return(&youtube.SearchResponse{
						Items: []youtube.SearchItem{
							{
								ID: youtube.SearchID{
									PlaylistID: "sampleID",
								},
							},
						},
					}, nil).
					Once()
				m.
					On("GetPlaylist", "sampleID").
					Return(&youtube.Playlist{
						ID:    "sampleID",
						Title: "sample artist – sample album",
					}, nil).
					Once()
			},
			expectedAlbum: &Entity{
				ID:       "sampleID",
				Title:    "sample album",
				Artist:   "sample artist",
				URL:      "https://www.youtube.com/playlist?list=sampleID",
				Provider: Youtube,
				Type:     Album,
			},
		},
		{
			name:       "not found query",
			artist:     "not found artist",
			searchName: "not found name",
			mockClient: func(m *youtube.ClientMock) {
				m.
					On("SearchPlaylist", "not found artist – not found name").
					Return(nil, youtube.NotFoundError).
					Once()
			},
			expectedAlbum: nil,
			expectedErr:   EntityNotFoundError,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			clientMock := &youtube.ClientMock{}
			tt.mockClient(clientMock)

			a := newYoutubeAdapter(clientMock)

			result, err := a.SearchAlbum(t.Context(), tt.artist, tt.searchName)

			if tt.expectedErr != nil {
				require.ErrorIs(t, err, tt.expectedErr)
			} else {
				require.NoError(t, err)
				require.Equal(t, tt.expectedAlbum, result)
			}

			clientMock.AssertExpectations(t)
		})
	}
}

func TestYoutubeAdapter_cleanAndSplitTitle(t *testing.T) {
	tests := []struct {
		title          string
		expectedArtist string
		expectedEntity string
	}{
		{
			title:          "rick astley - never gonna give you up",
			expectedArtist: "rick astley",
			expectedEntity: "never gonna give you up",
		},
		{
			title:          "radiohead amnesiac (2001)",
			expectedArtist: "radiohead",
			expectedEntity: "amnesiac",
		},
		{
			title:          "artist | title [official music video]",
			expectedArtist: "artist",
			expectedEntity: "title",
		},
		{
			title:          "band {live} - song",
			expectedArtist: "band",
			expectedEntity: "song",
		},
		{
			title:          "Michael Jackson - Billie Jean",
			expectedArtist: "Michael Jackson",
			expectedEntity: "Billie Jean",
		},
		{
			title:          "queen – bohemian rhapsody (official video)",
			expectedArtist: "queen",
			expectedEntity: "bohemian rhapsody",
		},
		{
			title:          "adele | someone like you",
			expectedArtist: "adele",
			expectedEntity: "someone like you",
		},
		{
			title:          "the beatles - hey jude [HQ]",
			expectedArtist: "the beatles",
			expectedEntity: "hey jude",
		},
		{
			title:          "coldplay – yellow (official video)",
			expectedArtist: "coldplay",
			expectedEntity: "yellow",
		},
	}
	for _, test := range tests {
		adapter := &YoutubeAdapter{}
		artist, entity := adapter.cleanAndSplitTitle(test.title)
		require.Equal(t, test.expectedArtist, artist)
		require.Equal(t, test.expectedEntity, entity)
	}
}
