package youtube

import (
	"fmt"
	"regexp"
	"strings"
)

const (
	autogeneratedPlaylistTitlePrefix = "Album - "
)

type Playlist struct {
	ID           string
	Title        string
	ChannelTitle string
}

var PlaylistRe = regexp.MustCompile(`(?:youtube\.com/playlist\?list=|youtu\.be/playlist\?list=)([a-zA-Z0-9_-]+)`)

func (p *Playlist) URL() string {
	return fmt.Sprintf("https://www.youtube.com/playlist?list=%s", p.ID)
}

func (p *Playlist) IsAutogenerated() bool {
	return strings.HasPrefix(p.Title, autogeneratedPlaylistTitlePrefix)
}

func (p *Playlist) Album() string {
	if !p.IsAutogenerated() {
		return p.Title
	}
	return strings.TrimPrefix(p.Title, autogeneratedPlaylistTitlePrefix)
}
