package youtube

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestPlaylist_URL(t *testing.T) {
	playlist := Playlist{ID: "PLMC9KNkIncKtPzgY-5rmhvj7fax8fdxoj"}
	result := playlist.URL()
	require.Equal(t, "https://www.youtube.com/playlist?list=PLMC9KNkIncKtPzgY-5rmhvj7fax8fdxoj", result)
}

func TestPlaylist_IsAutogenerated(t *testing.T) {
	tests := []struct {
		name  string
		title string
		want  bool
	}{
		{
			name:  "not autogenerated",
			title: "sample not autogenerated title",
			want:  false,
		},
		{
			name:  "autogenerated",
			title: "Album - David Bowie",
			want:  true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			v := &Playlist{Title: tt.title}
			require.Equal(t, tt.want, v.IsAutogenerated())
		})
	}
}

func TestPlaylist_Album(t *testing.T) {
	tests := []struct {
		name  string
		title string
		want  string
	}{
		{
			name:  "not autogenerated",
			title: "Space Oddity",
			want:  "Space Oddity",
		},
		{
			name:  "autogenerated",
			title: "Album - Space Oddity",
			want:  "Space Oddity",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			p := &Playlist{Title: tt.title}
			require.Equal(t, tt.want, p.Album())
		})
	}
}
