package youtube

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestVideo_URL(t *testing.T) {
	video := Video{ID: "dQw4w9WgXcQ"}
	result := video.URL()
	require.Equal(t, "https://www.youtube.com/watch?v=dQw4w9WgXcQ", result)
}

func TestVideo_IsAutogenerated(t *testing.T) {
	tests := []struct {
		name        string
		description string
		want        bool
	}{
		{
			name:        "not autogenerated",
			description: "sample not autogenerated description",
			want:        false,
		},
		{
			name: "autogenerated",
			description: "Provided to YouTube by Parlophone UK\n\nSpace Oddity (2015 Remaster) · " +
				"David Bowie\n\nDavid Bowie (aka Space Oddity)\n\n℗ 1969, 2015 Jones/Tintoretto Entertainment Company " +
				"LLC under exclusive licence to Parlophone Records Ltd, a Warner Music Group Company\n\nEngineer: " +
				"Barry Sheffield\nAcoustic  Guitar: David Bowie\nKeyboards, Vocals: David Bowie\nProducer: " +
				"Gus Dudgeon\nBass: Herbie Flowers\nUnknown: Ken Scott\nUnknown: Ken Scott\nEngineer: Malcolm Toft\n" +
				"Guitar: Mick Wayne\nRemastering  Engineer: Ray Staff\nMellotron: Rick Wakeman\nDrums: Terry Cox\n" +
				"Writer: David Bowie\n\nAuto-generated by YouTube.",
			want: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			v := &Video{Description: tt.description}
			require.Equal(t, tt.want, v.IsAutogenerated())
		})
	}
}

func TestVideo_Artist(t *testing.T) {
	tests := []struct {
		name         string
		channelTitle string
		want         string
	}{
		{
			name:         "not autogenerated",
			channelTitle: "David Bowie",
			want:         "",
		},
		{
			name:         "autogenerated",
			channelTitle: "David Bowie - Topic",
			want:         "David Bowie",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			v := &Video{ChannelTitle: tt.channelTitle}
			require.Equal(t, tt.want, v.Artist())
		})
	}
}
