package youtube

import (
	"fmt"
	"regexp"
	"strings"
)

const (
	autogeneratedVideoDescriptionSubstring = "Auto-generated by YouTube"
	autogeneratedVideoChannelTitleSuffix   = " - Topic"
)

type Video struct {
	ID           string
	Title        string
	ChannelTitle string
	Description  string
}

var VideoRe = regexp.MustCompile(`(?:youtu\.be/|youtube\.com/watch\?v=)([a-zA-Z0-9_-]{11})`)

func (v *Video) URL() string {
	return fmt.Sprintf("https://www.youtube.com/watch?v=%s", v.ID)
}

func (v *Video) IsAutogenerated() bool {
	return strings.Contains(v.Description, autogeneratedVideoDescriptionSubstring)
}

func (v *Video) Artist() string {
	if !strings.HasSuffix(v.ChannelTitle, autogeneratedVideoChannelTitleSuffix) {
		return ""
	}
	return strings.TrimSuffix(v.ChannelTitle, autogeneratedVideoChannelTitleSuffix)
}
